# Generated by Django 2.0 on 2017-12-27 11:01

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20171227_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('code', models.CharField(default=auth_app.models.get_random_code, max_length=32)),
                ('expiration_date', models.DateTimeField(default=auth_app.models.get_now_plus_1_day)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
