# Generated by Django 2.0 on 2017-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
