# Generated by Django 2.0 on 2018-01-04 09:57

import auth_app.models
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Адрес електронной почты')),
                ('tel_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона')),
                ('viber_id', models.CharField(max_length=64, null=True)),
                ('viber_secret_message', models.CharField(default=auth_app.models.get_random_code, max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('code', models.CharField(default=auth_app.models.get_random_code, max_length=32)),
                ('expiration_date', models.DateTimeField(default=auth_app.models.get_now_plus_1_day)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
