# Generated by Django 2.0 on 2017-12-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_from', models.CharField(max_length=50, verbose_name='Станция отправления')),
                ('station_till', models.CharField(max_length=50, verbose_name='Станция назначения')),
                ('date_dep', models.DateField(verbose_name='Дата отправления')),
                ('coach_type', models.CharField(choices=[('П', 'Плацкарт'), ('К', 'Купе'), ('Л', 'Люкс')], max_length=1, verbose_name='Тип места')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальность')),
            ],
        ),
    ]
