# Generated by Django 2.0 on 2017-12-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(max_length=8)),
                ('date_from', models.DateTimeField()),
                ('date_till', models.DateTimeField()),
                ('carriage', models.CharField(max_length=2)),
                ('coaches', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания запроса')),
            ],
        ),
        migrations.CreateModel(
            name='SearchingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_from', models.CharField(max_length=50, verbose_name='Станция отправления')),
                ('station_till', models.CharField(max_length=50, verbose_name='Станция назначения')),
                ('date_dep', models.CharField(max_length=10, verbose_name='Дата отправления')),
                ('coach_type', models.CharField(choices=[('П', 'Плацкарт'), ('К', 'Купе'), ('Л', 'Люкс')], max_length=1, verbose_name='Тип места')),
                ('amount_of_coaches', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SearchRequests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_actual', '-create_date'],
            },
        ),
        migrations.AddField(
            model_name='result',
            name='searching_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search_app.SearchingInfo'),
        ),
    ]
