# Generated by Django 2.0 on 2017-12-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failresult',
            options={},
        ),
    ]
