# Generated by Django 2.0 on 2017-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinginfo',
            name='coach_type',
            field=models.CharField(choices=[('П', 'Плацкарт'), ('К', 'Купе'), ('Л', 'Люкс')], max_length=1, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='searchinginfo',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания запроса'),
        ),
        migrations.AlterField(
            model_name='searchinginfo',
            name='date_dep',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='searchinginfo',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='searchinginfo',
            name='station_from',
            field=models.CharField(max_length=50, verbose_name='Станция отправления'),
        ),
        migrations.AlterField(
            model_name='searchinginfo',
            name='station_till',
            field=models.CharField(max_length=50, verbose_name='Станция назначения'),
        ),
    ]
