# Generated by Django 2.0 on 2017-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinginfo',
            name='date_dep',
            field=models.CharField(max_length=10, verbose_name='Дата отправления'),
        ),
    ]
