# Generated by Django 2.0 on 2017-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20171227_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchinginfo',
            name='get_best',
            field=models.BooleanField(default=False, verbose_name='Искать только лучшие'),
        ),
        migrations.AddField(
            model_name='searchinginfo',
            name='get_good',
            field=models.BooleanField(default=False, verbose_name='Искать только хорошие'),
        ),
    ]
