# Generated by Django 2.0 on 2018-01-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_searchinginfo_date_dep_in_datetime_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchinginfo',
            options={'ordering': ['-is_actual', '-create_date']},
        ),
    ]
