# Generated by Django 2.0 on 2018-01-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20180103_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchinginfo',
            options={'ordering': ['-is_actual', 'create_date']},
        ),
    ]
