# Generated by Django 2.0 on 2018-01-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2)),
                ('coaches', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FailResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail_message', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_from', models.CharField(max_length=50, verbose_name='Станция отправления')),
                ('station_till', models.CharField(max_length=50, verbose_name='Станция назначения')),
                ('date_dep', models.CharField(max_length=10, verbose_name='Дата отправления')),
                ('date_dep_in_datetime_format', models.DateField(null=True)),
                ('coach_type', models.CharField(choices=[('П', 'Плацкарт'), ('К', 'Купе'), ('Л', 'Люкс')], max_length=1, verbose_name='Тип места')),
                ('amount_of_coaches', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('get_good', models.BooleanField(default=False, verbose_name='Искать только хорошие')),
                ('get_best', models.BooleanField(default=False, verbose_name='Искать только лучшие')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SearchRequests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_dep_in_datetime_format'],
            },
        ),
        migrations.CreateModel(
            name='SuccessResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(max_length=8)),
                ('date_from', models.DateTimeField()),
                ('date_till', models.DateTimeField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('searching_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_results', to='search_app.SearchingInfo')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='failresult',
            name='searching_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fail_result', to='search_app.SearchingInfo'),
        ),
        migrations.AddField(
            model_name='carriage',
            name='success_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriages', to='search_app.SuccessResult'),
        ),
    ]
