# Generated by Django 2.0 on 2018-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='successresult',
            name='train',
            field=models.CharField(max_length=128),
        ),
    ]
